typography_spectrum: 0.48183430009521544
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5748699388932437
  lightness: 0.5441738667432219
  saturation: 0.5765180930029601
  rhythmicContrast: 0.6745248795486987
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.552592100109905
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Nick Jones
  email: nick@narrowdesign.com
  url: 'http://narrowdesign.com'
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e20ff65-2d05-494a-85c8-edeb7fce8c32.png'
name: Various Projects
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/be77ef71-9950-4504-b2c4-e7130e98fb45.png'
title: "Too many projects started. Too few seen through. This is a place to keep track of them so they don't get lost."
purpose: []
