typography_spectrum: 0.48183430009521544
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5748699388932437
  lightness: 0.5441738667432219
  saturation: 0.5765180930029601
  rhythmicContrast: 0.6745248795486987
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.552592100109905
analytics:
  google: null
  facebook: null
  twitter: null
name: jones
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
